apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmdbdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cmdbdemo
  template:
    metadata:
      labels:
        name: cmdbdemo
    spec:
      serviceAccountName: cmdbdemo
      containers:
        - name: cmdbdemo
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - cmdbdemo
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cmdbdemo"
