kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cmdbdemo
subjects:
- kind: ServiceAccount
  name: cmdbdemo
roleRef:
  kind: Role
  name: cmdbdemo
  apiGroup: rbac.authorization.k8s.io
